apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcheck-operator
  labels:
    app: netcheck-operator
spec:
  # Please note that there is only one replica. Keep it that way!
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: netcheck-operator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
      labels:
        app: netcheck-operator
    spec:
      serviceAccountName: netcheck-operator-account
      containers:
      - name: netcheck
        image: ghcr.io/hardbyte/netcheck-operator:main
        imagePullPolicy: Always
        ports:
          - name: liveness
            containerPort: 8080
            protocol: TCP
          - name: metrics
            containerPort: 9090
            protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: liveness
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
